### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by wsguede** [BMBros/TriviaAPI#5]
Use firebase as a backed.

- [ ] Authentication
    - Anon (game player)
    - User (game owner)

- [ ] [Database](https://github.com/BMBros/TriviaAPI/issues/6)
  - [SPIKE] Come up with game scheme
      - DB - Game Setup
      - DB - Game In-Progress
          - This would be the main websocket
      - ??
- [ ] Can we host react app on firebase?
    - [SPIKE]
    - CORS?

**Comment by sdg9** [comment]
I can't edit your comment, ideally link Database spike to #6
